# Generated by Django 5.0.2 on 2024-02-08 21:20

import apps.shared.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('language', models.CharField(choices=[('uz', 'UZBEK'), ('en', 'ENGLISH'), ('ru', 'RUSSIAN')], default=apps.shared.utils.Language['UZBEK'], max_length=100)),
                ('user_status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('deleted', 'DELETED')], default=apps.shared.utils.UserStatus['ACTIVE'], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('answers', models.JSONField()),
                ('file', models.FileField(blank=True, null=True, upload_to='questions')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('answer', models.JSONField()),
                ('correct_answers', models.JSONField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.botuser')),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
