# Generated by Django 5.0.2 on 2024-02-08 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_description_alter_botuser_last_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionanswer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.botuser'),
        ),
        migrations.DeleteModel(
            name='BotUser',
        ),
    ]
