# Generated by Django 5.0.2 on 2024-02-09 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_userquestionanswer_user_delete_botuser'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.botuser'),
        ),
        migrations.AlterField(
            model_name='question',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userquestionanswer',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
