# Generated by Django 5.0.2 on 2024-02-09 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_question_user_alter_question_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquestionanswer',
            name='answer',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='userquestionanswer',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
