# Generated by Django 5.0.2 on 2024-02-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_userquestionanswer_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
