# Generated by Django 5.0.2 on 2024-02-09 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_alter_question_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='userquestionanswer',
            old_name='status',
            new_name='is_active',
        ),
    ]
