# Generated by Django 5.0.2 on 2024-02-08 21:43

import apps.shared.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(choices=[('uz', 'UZBEK'), ('en', 'ENGLISH'), ('ru', 'RUSSIAN')], default=apps.shared.utils.Language['UZBEK'], max_length=100)),
                ('user_status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE'), ('deleted', 'DELETED')], default=apps.shared.utils.UserStatus['ACTIVE'], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
